### ISSUE TITLE
Is this host only?

### ISSUE THREAD

**Issue by spinmastercodes** [Ian0526/KillableEnemies#2]
Im just wondering. the boys are incredibly scared of viruses (whimps) but anyway, yeh.

**Comment by Ian0526** [comment]
Completely understandable. All clients will need it because there are RPC methods being called. I could make a lite version that only requires host installation but that wouldn't be for a couple of days. Also, my real identity is tied to this Git account, let alone my last name is in the source. It would be incredibly stupid to backdoor something with that info available lol.

If it reassures them, you could clone and evaluate the code yourself. You'd need to add in your own references for it to build though. Alternatively, you can also scan the .dll provided in Thunderstore with some sort of AV.

Let me know if I can help any other way, sorry about that.

**Comment by spinmastercodes** [comment]
> Completely understandable. All clients will need it because there are RPC methods being called. I could make a lite version that only requires host installation but that wouldn't be for a couple of days. Also, my real identity is tied to this Git account, let alone my last name is in the source. It would be incredibly stupid to backdoor something with that info available lol.
> 
> If it reassures them, you could clone and evaluate the code yourself. You'd need to add in your own references for it to build though. Alternatively, you can also scan the .dll provided in Thunderstore with some sort of AV.
> 
> Let me know if I can help any other way, sorry about that.

its completely fine. dont do anymore work than you need to :D
